Add note cautioning against bothering with WARNS=6 until gcc improves (or -Wconversion is removed from WARNS=6) as it produces loads of false positives. The most entertaining of these that I've seen this afternoon:
games/hack/hack.apply.c:143:22: error: conversion to 'unsigned char:1' from 'int' may alter its value [-Werror=conversion]
   flags.move = multi = 0;
                      ^